/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClientID = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuditEntry = IDL.Record({
  'action' : IDL.Text,
  'entryTime' : Timestamp,
  'user' : IDL.Principal,
  'details' : IDL.Text,
});
export const BehaviorPattern = IDL.Record({
  'id' : IDL.Nat,
  'detectedAt' : Timestamp,
  'user' : IDL.Principal,
  'analyzedBy' : IDL.Principal,
  'patternDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'extendedRole' : IDL.Text,
  'department' : IDL.Text,
});
export const DocumentKey = IDL.Text;
export const KycDocument = IDL.Record({
  'pan' : IDL.Text,
  'documents' : IDL.Vec(DocumentKey),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
});
export const DocumentMeta = IDL.Record({
  'file' : ExternalBlob,
  'docType' : IDL.Text,
  'uploadTime' : Timestamp,
  'uploadedBy' : IDL.Principal,
});
export const MarginSnapshot = IDL.Record({
  'snapshotTime' : Timestamp,
  'date' : Timestamp,
  'marginAvailable' : IDL.Float64,
  'recordedBy' : IDL.Principal,
  'marginUsed' : IDL.Float64,
});
export const Thread = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'createdAt' : Timestamp,
  'authorizedUsers' : IDL.Vec(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func([ClientID, IDL.Text, ExternalBlob], [], []),
  'addMarginSnapshot' : IDL.Func([IDL.Float64, IDL.Float64, Timestamp], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBehaviorPattern' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ClientID], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Vec(IDL.Principal)], [IDL.Nat], []),
  'getAuditEntries' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'getBehaviorPattern' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BehaviorPattern)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientID], [IDL.Opt(KycDocument)], ['query']),
  'getDocument' : IDL.Func([DocumentKey], [IDL.Opt(DocumentMeta)], ['query']),
  'getMarginSnapshots' : IDL.Func([], [IDL.Vec(MarginSnapshot)], ['query']),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(Thread)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([ClientID, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClientID = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuditEntry = IDL.Record({
    'action' : IDL.Text,
    'entryTime' : Timestamp,
    'user' : IDL.Principal,
    'details' : IDL.Text,
  });
  const BehaviorPattern = IDL.Record({
    'id' : IDL.Nat,
    'detectedAt' : Timestamp,
    'user' : IDL.Principal,
    'analyzedBy' : IDL.Principal,
    'patternDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'extendedRole' : IDL.Text,
    'department' : IDL.Text,
  });
  const DocumentKey = IDL.Text;
  const KycDocument = IDL.Record({
    'pan' : IDL.Text,
    'documents' : IDL.Vec(DocumentKey),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
  });
  const DocumentMeta = IDL.Record({
    'file' : ExternalBlob,
    'docType' : IDL.Text,
    'uploadTime' : Timestamp,
    'uploadedBy' : IDL.Principal,
  });
  const MarginSnapshot = IDL.Record({
    'snapshotTime' : Timestamp,
    'date' : Timestamp,
    'marginAvailable' : IDL.Float64,
    'recordedBy' : IDL.Principal,
    'marginUsed' : IDL.Float64,
  });
  const Thread = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : Timestamp,
    'authorizedUsers' : IDL.Vec(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func([ClientID, IDL.Text, ExternalBlob], [], []),
    'addMarginSnapshot' : IDL.Func(
        [IDL.Float64, IDL.Float64, Timestamp],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBehaviorPattern' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ClientID], []),
    'createThread' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'getAuditEntries' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'getBehaviorPattern' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BehaviorPattern)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientID], [IDL.Opt(KycDocument)], ['query']),
    'getDocument' : IDL.Func([DocumentKey], [IDL.Opt(DocumentMeta)], ['query']),
    'getMarginSnapshots' : IDL.Func([], [IDL.Vec(MarginSnapshot)], ['query']),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(Thread)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([ClientID, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };