/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEntry {
  'action' : string,
  'entryTime' : Timestamp,
  'user' : Principal,
  'details' : string,
}
export interface BehaviorPattern {
  'id' : bigint,
  'detectedAt' : Timestamp,
  'user' : Principal,
  'analyzedBy' : Principal,
  'patternDescription' : string,
}
export type ClientID = bigint;
export type DocumentKey = string;
export interface DocumentMeta {
  'file' : ExternalBlob,
  'docType' : string,
  'uploadTime' : Timestamp,
  'uploadedBy' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface KycDocument {
  'pan' : string,
  'documents' : Array<DocumentKey>,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'updatedAt' : Timestamp,
  'address' : string,
}
export interface MarginSnapshot {
  'snapshotTime' : Timestamp,
  'date' : Timestamp,
  'marginAvailable' : number,
  'recordedBy' : Principal,
  'marginUsed' : number,
}
export interface Thread {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'createdAt' : Timestamp,
  'authorizedUsers' : Array<Principal>,
}
export type Timestamp = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'extendedRole' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<[ClientID, string, ExternalBlob], undefined>,
  'addMarginSnapshot' : ActorMethod<[number, number, Timestamp], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBehaviorPattern' : ActorMethod<[Principal, string], bigint>,
  'createClient' : ActorMethod<[string, string, string], ClientID>,
  'createThread' : ActorMethod<[string, Array<Principal>], bigint>,
  'getAuditEntries' : ActorMethod<[], Array<AuditEntry>>,
  'getBehaviorPattern' : ActorMethod<[bigint], [] | [BehaviorPattern]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientID], [] | [KycDocument]>,
  'getDocument' : ActorMethod<[DocumentKey], [] | [DocumentMeta]>,
  'getMarginSnapshots' : ActorMethod<[], Array<MarginSnapshot>>,
  'getThread' : ActorMethod<[bigint], [] | [Thread]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[ClientID, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];