/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEntry {
  'action' : string,
  'entryTime' : Timestamp,
  'user' : Principal,
  'details' : string,
}
export interface BehaviorPattern {
  'id' : bigint,
  'detectedAt' : Timestamp,
  'user' : Principal,
  'analyzedBy' : Principal,
  'patternDescription' : string,
}
export interface BulkClient {
  'pan' : string,
  'documents' : Array<DocumentKey>,
  'name' : string,
  'address' : string,
}
export type ClientId = bigint;
export interface CollateralRecord {
  'clientId' : ClientId,
  'marketValue' : number,
  'recordedAt' : Timestamp,
  'recordedBy' : Principal,
  'pledgeDate' : Timestamp,
  'quantity' : bigint,
  'securityName' : string,
}
export type DocumentKey = string;
export interface DocumentMeta {
  'file' : ExternalBlob,
  'docType' : string,
  'uploadTime' : Timestamp,
  'uploadedBy' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface GeneratedReport {
  'id' : bigint,
  'status' : string,
  'templateId' : string,
  'generatedAt' : Timestamp,
  'generatedBy' : Principal,
  'parameters' : string,
}
export interface KycDocument {
  'pan' : string,
  'documents' : Array<DocumentKey>,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'updatedAt' : Timestamp,
  'address' : string,
}
export interface MarginSnapshot {
  'snapshotTime' : Timestamp,
  'date' : Timestamp,
  'marginAvailable' : number,
  'recordedBy' : Principal,
  'marginUsed' : number,
}
export interface ReconciliationRun {
  'status' : string,
  'uploadDate' : Timestamp,
  'runId' : bigint,
  'rowCount' : bigint,
  'uploadedBy' : Principal,
}
export interface RegulatoryDeadline {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'dueDate' : Timestamp,
  'description' : string,
  'category' : string,
}
export interface ReportTemplate {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface StatementRow {
  'balance' : number,
  'date' : Timestamp,
  'description' : string,
  'recordedBy' : Principal,
  'amount' : number,
}
export interface Thread {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'createdAt' : Timestamp,
  'authorizedUsers' : Array<Principal>,
}
export type Timestamp = bigint;
export interface Trade {
  'trade_id' : string,
  'client_code' : string,
  'side' : string,
  'trade_date' : string,
  'security' : string,
  'segment' : string,
  'quantity' : bigint,
  'order_id' : string,
  'exchange' : string,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'extendedRole' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActiveClient' : ActorMethod<[ClientId], undefined>,
  'addDocument' : ActorMethod<[ClientId, string, ExternalBlob], undefined>,
  'addMarginSnapshot' : ActorMethod<[number, number, Timestamp], undefined>,
  'addRegulatoryDeadline' : ActorMethod<
    [string, string, Timestamp, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backendHealthCheck' : ActorMethod<[], boolean>,
  'bulkUploadClients' : ActorMethod<[Array<BulkClient>], Array<ClientId>>,
  'bulkUploadCollateral' : ActorMethod<[Array<CollateralRecord>], undefined>,
  'bulkUploadMarginSnapshots' : ActorMethod<[Array<MarginSnapshot>], undefined>,
  'bulkUploadStatementRows' : ActorMethod<[Array<StatementRow>], bigint>,
  'createBehaviorPattern' : ActorMethod<[Principal, string], bigint>,
  'createClient' : ActorMethod<[string, string, string], ClientId>,
  'createThread' : ActorMethod<[string, Array<Principal>], bigint>,
  'generateReport' : ActorMethod<[string, string], bigint>,
  'getActiveClients' : ActorMethod<[], Array<ClientId>>,
  'getAllClients' : ActorMethod<[], Array<KycDocument>>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getAuditEntries' : ActorMethod<[], Array<AuditEntry>>,
  'getBehaviorPattern' : ActorMethod<[bigint], [] | [BehaviorPattern]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientId], [] | [KycDocument]>,
  'getCollateralRecords' : ActorMethod<[], Array<CollateralRecord>>,
  'getDashboardMetrics' : ActorMethod<
    [],
    {
      'reconciliationRunCount' : bigint,
      'totalTrades' : bigint,
      'latestMarginAvailable' : number,
      'pendingDeadlines' : bigint,
      'totalClients' : bigint,
      'latestMarginUsed' : number,
    }
  >,
  'getDocument' : ActorMethod<[DocumentKey], [] | [DocumentMeta]>,
  'getGeneratedReports' : ActorMethod<[], Array<GeneratedReport>>,
  'getMarginSnapshots' : ActorMethod<[], Array<MarginSnapshot>>,
  'getReconciliationRun' : ActorMethod<[bigint], [] | [ReconciliationRun]>,
  'getReconciliationRuns' : ActorMethod<[], Array<ReconciliationRun>>,
  'getRegulatoryDeadlines' : ActorMethod<[], Array<RegulatoryDeadline>>,
  'getReportTemplates' : ActorMethod<[], Array<ReportTemplate>>,
  'getStatementRows' : ActorMethod<[], Array<StatementRow>>,
  'getThread' : ActorMethod<[bigint], [] | [Thread]>,
  'getTradesByClientCode' : ActorMethod<[string], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importTrades' : ActorMethod<[Array<Trade>], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeActiveClient' : ActorMethod<[ClientId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[ClientId, string, string, string], undefined>,
  'updateRegulatoryDeadlineStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];