/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Thread {
    id: bigint;
    title: string;
    creator: Principal;
    createdAt: Timestamp;
    authorizedUsers: Array<Principal>;
}
export interface StatementRow {
    balance: number;
    date: Timestamp;
    description: string;
    recordedBy: Principal;
    amount: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Trade {
    trade_id: string;
    client_code: string;
    side: string;
    trade_date: string;
    security: string;
    segment: string;
    quantity: bigint;
    order_id: string;
    exchange: string;
    price: number;
}
export interface RegulatoryDeadline {
    id: bigint;
    status: string;
    title: string;
    createdAt: Timestamp;
    createdBy: Principal;
    dueDate: Timestamp;
    description: string;
    category: string;
}
export interface KycDocument {
    pan: string;
    documents: Array<DocumentKey>;
    name: string;
    createdAt: Timestamp;
    createdBy: Principal;
    updatedAt: Timestamp;
    address: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DocumentMeta {
    file: ExternalBlob;
    docType: string;
    uploadTime: Timestamp;
    uploadedBy: Principal;
}
export interface GeneratedReport {
    id: bigint;
    status: string;
    templateId: string;
    generatedAt: Timestamp;
    generatedBy: Principal;
    parameters: string;
}
export type DocumentKey = string;
export interface AuditEntry {
    action: string;
    entryTime: Timestamp;
    user: Principal;
    details: string;
}
export interface MarginSnapshot {
    snapshotTime: Timestamp;
    date: Timestamp;
    marginAvailable: number;
    recordedBy: Principal;
    marginUsed: number;
}
export interface ReportTemplate {
    id: string;
    name: string;
    description: string;
    category: string;
}
export interface BulkClient {
    pan: string;
    documents: Array<DocumentKey>;
    name: string;
    address: string;
}
export interface BehaviorPattern {
    id: bigint;
    detectedAt: Timestamp;
    user: Principal;
    analyzedBy: Principal;
    patternDescription: string;
}
export interface CollateralRecord {
    clientId: ClientId;
    marketValue: number;
    recordedAt: Timestamp;
    recordedBy: Principal;
    pledgeDate: Timestamp;
    quantity: bigint;
    securityName: string;
}
export interface ReconciliationRun {
    status: string;
    uploadDate: Timestamp;
    runId: bigint;
    rowCount: bigint;
    uploadedBy: Principal;
}
export type ClientId = bigint;
export interface UserProfile {
    name: string;
    email: string;
    extendedRole: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addActiveClient(clientId: ClientId): Promise<void>;
    addDocument(clientId: ClientId, docType: string, blob: ExternalBlob): Promise<void>;
    addMarginSnapshot(available: number, used: number, timestamp: Timestamp): Promise<void>;
    addRegulatoryDeadline(title: string, description: string, dueDate: Timestamp, category: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backendHealthCheck(): Promise<boolean>;
    bulkUploadClients(clientsInput: Array<BulkClient>): Promise<Array<ClientId>>;
    bulkUploadCollateral(collateralInput: Array<CollateralRecord>): Promise<void>;
    bulkUploadMarginSnapshots(snapshots: Array<MarginSnapshot>): Promise<void>;
    bulkUploadStatementRows(rowsInput: Array<StatementRow>): Promise<bigint>;
    createBehaviorPattern(user: Principal, description: string): Promise<bigint>;
    createClient(name: string, pan: string, address: string): Promise<ClientId>;
    createThread(title: string, authorizedUsers: Array<Principal>): Promise<bigint>;
    generateReport(templateId: string, parameters: string): Promise<bigint>;
    getActiveClients(): Promise<Array<ClientId>>;
    getAllClients(): Promise<Array<KycDocument>>;
    getAllTrades(): Promise<Array<Trade>>;
    getAuditEntries(): Promise<Array<AuditEntry>>;
    getBehaviorPattern(patternId: bigint): Promise<BehaviorPattern | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(clientId: ClientId): Promise<KycDocument | null>;
    getCollateralRecords(): Promise<Array<CollateralRecord>>;
    getDashboardMetrics(): Promise<{
        reconciliationRunCount: bigint;
        totalTrades: bigint;
        latestMarginAvailable: number;
        pendingDeadlines: bigint;
        totalClients: bigint;
        latestMarginUsed: number;
    }>;
    getDocument(key: DocumentKey): Promise<DocumentMeta | null>;
    getGeneratedReports(): Promise<Array<GeneratedReport>>;
    getMarginSnapshots(): Promise<Array<MarginSnapshot>>;
    getReconciliationRun(runId: bigint): Promise<ReconciliationRun | null>;
    getReconciliationRuns(): Promise<Array<ReconciliationRun>>;
    getRegulatoryDeadlines(): Promise<Array<RegulatoryDeadline>>;
    getReportTemplates(): Promise<Array<ReportTemplate>>;
    getStatementRows(): Promise<Array<StatementRow>>;
    getThread(threadId: bigint): Promise<Thread | null>;
    getTradesByClientCode(client_code: string): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importTrades(trades: Array<Trade>): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    removeActiveClient(clientId: ClientId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(clientId: ClientId, name: string, pan: string, address: string): Promise<void>;
    updateRegulatoryDeadlineStatus(deadlineId: bigint, status: string): Promise<void>;
}
import type { BehaviorPattern as _BehaviorPattern, DocumentMeta as _DocumentMeta, ExternalBlob as _ExternalBlob, KycDocument as _KycDocument, ReconciliationRun as _ReconciliationRun, Thread as _Thread, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addActiveClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActiveClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActiveClient(arg0);
            return result;
        }
    }
    async addDocument(arg0: ClientId, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addMarginSnapshot(arg0: number, arg1: number, arg2: Timestamp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarginSnapshot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarginSnapshot(arg0, arg1, arg2);
            return result;
        }
    }
    async addRegulatoryDeadline(arg0: string, arg1: string, arg2: Timestamp, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegulatoryDeadline(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegulatoryDeadline(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backendHealthCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.backendHealthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backendHealthCheck();
            return result;
        }
    }
    async bulkUploadClients(arg0: Array<BulkClient>): Promise<Array<ClientId>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadClients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadClients(arg0);
            return result;
        }
    }
    async bulkUploadCollateral(arg0: Array<CollateralRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadCollateral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadCollateral(arg0);
            return result;
        }
    }
    async bulkUploadMarginSnapshots(arg0: Array<MarginSnapshot>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadMarginSnapshots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadMarginSnapshots(arg0);
            return result;
        }
    }
    async bulkUploadStatementRows(arg0: Array<StatementRow>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUploadStatementRows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUploadStatementRows(arg0);
            return result;
        }
    }
    async createBehaviorPattern(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBehaviorPattern(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBehaviorPattern(arg0, arg1);
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2);
            return result;
        }
    }
    async createThread(arg0: string, arg1: Array<Principal>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThread(arg0, arg1);
            return result;
        }
    }
    async generateReport(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0, arg1);
            return result;
        }
    }
    async getActiveClients(): Promise<Array<ClientId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveClients();
            return result;
        }
    }
    async getAllClients(): Promise<Array<KycDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return result;
        }
    }
    async getAuditEntries(): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditEntries();
            return result;
        }
    }
    async getBehaviorPattern(arg0: bigint): Promise<BehaviorPattern | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorPattern(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorPattern(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<KycDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollateralRecords(): Promise<Array<CollateralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollateralRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollateralRecords();
            return result;
        }
    }
    async getDashboardMetrics(): Promise<{
        reconciliationRunCount: bigint;
        totalTrades: bigint;
        latestMarginAvailable: number;
        pendingDeadlines: bigint;
        totalClients: bigint;
        latestMarginUsed: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getDocument(arg0: DocumentKey): Promise<DocumentMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGeneratedReports(): Promise<Array<GeneratedReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeneratedReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeneratedReports();
            return result;
        }
    }
    async getMarginSnapshots(): Promise<Array<MarginSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarginSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarginSnapshots();
            return result;
        }
    }
    async getReconciliationRun(arg0: bigint): Promise<ReconciliationRun | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReconciliationRun(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReconciliationRun(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReconciliationRuns(): Promise<Array<ReconciliationRun>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReconciliationRuns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReconciliationRuns();
            return result;
        }
    }
    async getRegulatoryDeadlines(): Promise<Array<RegulatoryDeadline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegulatoryDeadlines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegulatoryDeadlines();
            return result;
        }
    }
    async getReportTemplates(): Promise<Array<ReportTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportTemplates();
            return result;
        }
    }
    async getStatementRows(): Promise<Array<StatementRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatementRows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatementRows();
            return result;
        }
    }
    async getThread(arg0: bigint): Promise<Thread | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThread(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThread(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByClientCode(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByClientCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByClientCode(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async importTrades(arg0: Array<Trade>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importTrades(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importTrades(arg0);
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeActiveClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeActiveClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeActiveClient(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: ClientId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateRegulatoryDeadlineStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegulatoryDeadlineStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegulatoryDeadlineStatus(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_DocumentMeta_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentMeta): Promise<DocumentMeta> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BehaviorPattern]): BehaviorPattern | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KycDocument]): KycDocument | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentMeta]): Promise<DocumentMeta | null> {
    return value.length === 0 ? null : await from_candid_DocumentMeta_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReconciliationRun]): ReconciliationRun | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Thread]): Thread | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: _ExternalBlob;
    docType: string;
    uploadTime: _Timestamp;
    uploadedBy: Principal;
}): Promise<{
    file: ExternalBlob;
    docType: string;
    uploadTime: Timestamp;
    uploadedBy: Principal;
}> {
    return {
        file: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.file),
        docType: value.docType,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
